### ISSUE TITLE
error with jaxtyping

### ISSUE THREAD

**Issue by Duuuuu** [pointrix-project/msplat#12]
Hello, when I install the msplat project, there is an error:
"ERROR: Could not find a version that satisfies the requirement jaxtyping (from msplat) (from versions: none)
ERROR: No matching distribution found for jaxtyping".
I check this link https://pypi.org/project/jaxtyping/, and trying to install jaxtyping by "pip install jaxtyping". However, the latest jaxtyping need python>=3.9, but the msplat just need python>=3.，and as I'm trying to use the msplat in 3d gaussian splatting(which need python=3.7), so I am wondering which version of jaxtyping should i install? Or how can I install msplat properly？
Looking for your answer! 
Thanks so much!!!

**Comment by yGaoJiany** [comment]
Consider trying Python 3.9. In my experience, the 3DGS library works perfectly with Python 3.9.

**Comment by Duuuuu** [comment]
Sorry to reply now. I try the python3.9 and install these package 
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.9.19
  - pip
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
and with CUDA11.8 installed in the windows10 (as the 3DGS required). Now, the jaxtyping problem has been solved but I still can't install msplat. 

These are the error messages :
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(338): error: invalid 
combination of type specifiers
     
      C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(338): error: expected an identifier
     
      C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(379): error: expected a member name
     
      3 errors detected in the compilation of "D:/Code/GaussianSplatting/comment_3DGS/submodules/msplat/msplat/src/sort_gaussian.cu".       
 an identifier
     
      C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(379): error: expected a member name
     
      3 errors detected in the compilation of "D:/Code/GaussianSplatting/comment_3DGS/submodules/msplat/msplat/src/sort_gaussian.cu".       

      C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(379): error: expected a member name

      3 errors detected in the compilation of "D:/Code/GaussianSplatting/comment_3DGS/submodules/msplat/msplat/src/sort_gaussian.cu".       
      C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(379): error: expected a member name

      3 errors detected in the compilation of "D:/Code/GaussianSplatting/comment_3DGS/submodules/msplat/msplat/src/sort_gaussian.cu".       
 a member name

      3 errors detected in the compilation of "D:/Code/GaussianSplatting/comment_3DGS/submodules/msplat/msplat/src/sort_gaussian.cu".       

      3 errors detected in the compilation of "D:/Code/GaussianSplatting/comment_3DGS/submodules/msplat/msplat/src/sort_gaussian.cu".       
      3 errors detected in the compilation of "D:/Code/GaussianSplatting/comment_3DGS/submodules/msplat/msplat/src/sort_gaussian.cu".       
      sort_gaussian.cu
      sort_gaussian.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for msplat
  Running setup.py clean for msplat
Failed to build msplat
ERROR: Could not build wheels for msplat, which is required to install pyproject.toml-based projects

These seem like something wrong with the cuda version? Can you give me some advice? Or what is your environment like? Maybe I can try to install the same environment with you~
Thank you so much!!!
