### ISSUE TITLE
ModuleNotFoundError: No module named 'msplat._C'

### ISSUE THREAD

**Issue by xxlbigbrother** [pointrix-project/msplat#3]
Very good project, but after pip install. After completion, I tried to import msplat and reported an error. The error was ModuleNotFoundError: No module named 'msplat._C'. What is the problem? urgent need of help

**Comment by yGaoJiany** [comment]
If you have a folder named _msplat_ in the same folder as that script that imports msplat, it's possible that you may have this issue.

**Comment by CA-TT-AC** [comment]
Hi, have u addressed this problem?

**Comment by CA-TT-AC** [comment]
> Hi, have u addressed this problem?

I forgot to **``pip install .``** . 


Don't be as stupid as me! XD

**Comment by xxlbigbrother** [comment]
> If you have a folder named _msplat_ in the same folder as that script that imports msplat, it's possible that you may have this issue.

Thanks, I had solved the problem, forgot to reply, thank you again!
