### ISSUE TITLE
There's strange behavior when adjust znear.

### ISSUE THREAD

**Issue by Yuhuoo** [pointrix-project/msplat#9]
Why does the performance of msplat vary so significantly when adjusting znear?

<img width="997" alt="image" src="https://github.com/pointrix-project/msplat/assets/91204817/44ebfc9a-618d-406a-a27b-c6e488b47a7e">

**Comment by Yuhuoo** [comment]
I tried the same settings in native 3D Gaussian Splatting.  But the results don’t seem to have changed much.

<img width="649" alt="image" src="https://github.com/pointrix-project/msplat/assets/91204817/6e494405-dc9a-4537-82be-4530058f509a">

**Comment by yGaoJiany** [comment]
Hmm, this looks weird. In MSplat, there isn't a concept of _znear_ since we utilize _Intrinsics_ /_Extrinsics_ rather than the _Model_/_View_/_Projection_ Matrix. Is there a way for me to replicate this experiment?

**Comment by yGaoJiany** [comment]
Please refer to: https://github.com/pointrix-project/msplat/issues/6#issuecomment-2116971018, where I replaced the _original 3dgs renderer_ to _msplat renderer_. Only _FoVx_, _FoVy_, _image_width_, _image_height_, and _world_view_transform_ from _viewpoint_camera_ are utilized while _z_near_ is not. 🤔
